[package]
name = "RustyTetris"
version = "0.1.0"
authors = ["gcx11 <gcx11@seznam.cz>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"
rand = "0.6.5"
num = "0.2"
num-traits = "0.2"
num-derive = "0.2"
enum-length-derive = { path = "enum-length-derive" }